version: 2
updates:
  # Keeps npm dependencies updated (package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  # Keeps GitHub Actions updated
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
